@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour redémarrerJeu

participant ":JeuDeDes" as c
participant "joueurs:\nMap<String,Joueur>" as j

->c : redemarrerJeu()
note over c,j
selon Contrôleur
(JeuDeDés est l'objet racine)
end note

c->j : clear()
note right
selon Expert
end note

@enduml
